name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare dist folder
        run: |
          rm -rf dist
          mkdir -p dist
          rsync -av --exclude '.git' --exclude '.github' --exclude 'dist' ./ dist/
          rm -rf dist/.git dist/.github

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          keep_files: true
