name: PR Preview

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site
        run: |
          rsync -a --exclude '.git' --exclude '.github' --exclude 'dist' ./ dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          destination_dir: pr-${{ github.event.number }}
          keep_files: true

      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const {owner, repo} = context.repo;
            const url = `https://${owner}.github.io/${repo}/pr-${prNumber}/`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner,
              repo,
              body: `Preview: ${url}`
            });
